name: "CrystalAPITest"
version: "${version}"
main: "io.sapphiremc.crystal.testing.CrystalTestPlugin"
description: "Test plugin for crystal api"
api-version: "1.18"
softdepend:
  - PlaceholderAPI
  - Vault
  - Gold
  - LuckPerms

commands:
  crystal:
    description: "Main command"
    permission: "crystal.admin"

permissions:
  crystal.admin:
    description: "Admin permission"
    default: op
