name: Deploy
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Deploy to repository
        run: ./gradlew -Dorg.gradle.parallel=true publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_sapphireUsername: ${{ secrets.DEPLOY_USERNAME }}
          ORG_GRADLE_PROJECT_sapphirePassword: ${{ secrets.DEPLOY_PASSWORD }}
      - name: Get project version
        id: get_version
        shell: bash
        run: |
          project_version=$(./gradlew -q --console=plain printVersion --no-daemon)
          echo version=$project_version >> $GITHUB_OUTPUT
      - name: Parse tag
        if: "!endsWith(steps.get_version.outputs.version, '-SNAPSHOT')"
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create release and changelog
        if: "!endsWith(steps.get_version.outputs.version, '-SNAPSHOT')"
        uses: MC-Machinations/auto-release-changelog@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Crystal ${{ steps.vars.outputs.tag }}
