name: Deploy
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Deploy to repository
        run: ./gradlew -Dorg.gradle.parallel=true publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_sapphireUsername: ${{ secrets.DEPLOY_USERNAME }}
          ORG_GRADLE_PROJECT_sapphirePassword: ${{ secrets.DEPLOY_PASSWORD }}
